### ISSUE TITLE
why is `dna_r10.4.1_e8.2_400bps_hac@v4.3.0` not valid?

### ISSUE THREAD

**Issue by istvankleijn** [epi2me-labs/wf-somatic-variation#37]
### Ask away!

I am attempting to run the pipeline on some data that was basecalled with `dna_r10.4.1_e8.2_400bps_hac@v4.3.0`. I would like to use the `ont-r10_dorado_hac_5khz` ClairS model according to https://github.com/HKU-BAL/ClairS/issues/33#issuecomment-2321039930. However, the v4.3 model does not pass parameter validation and I get the following error:
```
ERROR ~ * --override_basecaller_cfg: dna_r10.4.1_e8.2_400bps_hac@v4.3.0 is not a valid choice, pick one of:
    - dna_r10.4.1_e8.2_400bps_sup@v4.2.0
    - dna_r10.4.1_e8.2_400bps_hac@v4.2.0
    - dna_r10.4.1_e8.2_400bps_sup@v4.1.0
    - dna_r10.4.1_e8.2_400bps_hac@v4.1.0
    - dna_r10.4.1_e8.2_400bps_sup@v3.5.2
    - dna_r9.4.1_e8_hac@v3.3
    - dna_r9.4.1_e8_sup@v3.3
    - dna_r9.4.1_450bps_hac
    - dna_r9.4.1_450bps_hac_prom
 ```
Why is this the case, and is there a way to circumvent this? Should I even attempt to?

**Comment by RenzoTale88** [comment]
Hi @istvankleijn indeed ClairS has not been trained on the v4.3.0 model, as you can see in the table [here](https://github.com/HKU-BAL/ClairS?tab=readme-ov-file#pre-trained-models). If you want to use the `ont_r10_dorado_hac_5khz` model, you can provide `--override_basecaller_cfg dna_r10.4.1_e8.2_400bps_hac@v4.2.0` to your command line.

**Comment by istvankleijn** [comment]
@RenzoTale88 do I understand correctly that this will use the v4.2 Clair3 model? If so, how can I use the v4.3 Clair3 model with the `ont_r10_dorado_hac_5khz` ClairS model?

**Comment by RenzoTale88** [comment]
@istvankleijn there is no `ont_r10_dorado_hac_5khz` model for v4.3.0 specifically, since it has been trained on data basecalled with the 4.2.0 (see in the table linked [here](https://github.com/HKU-BAL/ClairS?tab=readme-ov-file#pre-trained-models)).

If you want to call variants from data basecalled with a different model (in your case the newer one 4.3.0)  but still use `ont_r10_dorado_hac_5khz`, then you'll have to run the workflow with `--override_basecaller_cfg dna_r10.4.1_e8.2_400bps_hac@v4.2.0`.

Andrea
